# Generated by Django 3.2 on 2022-12-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0003_alter_question_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('questionnaireAnswered', models.ManyToManyField(to='questionnaire.questionnaire')),
            ],
        ),
    ]
