# Generated by Django 3.2 on 2022-12-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_alter_question_questionnaire'),
        ('users', '0004_useranswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('answer', 'user')},
        ),
    ]
