# Generated by Django 3.2 on 2022-12-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
