# Generated by Django 3.2 on 2022-12-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20221206_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userAnswer',
        ),
    ]
